config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "instituitions#index"

  resources :instituitions
  resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

    has_many :instituition_courses
    has_many :instituitions, through: :instituition_courses

    scope :by_name, -> { order("name asc") }

    def update_course_rates!
        self.general_evaluation = instituition_courses.count > 0 ? (instituition_courses.sum(:course_evaluation).to_f/instituition_courses.count).round(2) : 0
        self.student_count = instituition_courses.sum(:students_count)
        self.save
    end

end

app/models/instituition.rb
class Instituition < ApplicationRecord

    has_many :instituition_courses, dependent: :destroy
    has_many :courses, through: :instituition_courses

    validates :name, presence: true

    scope :by_name, -> { order("name asc") }
    scope :by_evaluation, -> { order("evaluation asc") }

    accepts_nested_attributes_for :instituition_courses, allow_destroy: true, reject_if: :all_blank

    def update_instituition_rates!
        self.general_evaluation = instituition_courses.count != 0 ? (instituition_courses.sum(:course_evaluation).to_f/instituition_courses.count).round(2) : 0
        self.student_evaluation = instituition_courses.count != 0 ? (instituition_courses.sum(:students_evaluation).to_f/instituition_courses.count).round(2) : 0
        self.save
    end

end

app/models/instituition_course.rb
class InstituitionCourse < ApplicationRecord

    belongs_to :course
    belongs_to :instituition

    validates :instituition, :course, presence: true

    delegate :update_course_rates!, to: :course
    delegate :update_instituition_rates!, to: :instituition

    after_save :update_course_rates!
    after_save :update_instituition_rates!
    after_destroy :update_course_rates!
    after_destroy :update_instituition_rates!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index
        respond_to do |format|
            format.html
            format.json { render json: {data: Course.all} }
        end
    end
    
end

app/controllers/instituitions_controller.rb
class InstituitionsController < ApplicationController

    before_action :set_instituition, only: [:show, :edit, :update, :destroy]

    def index
        respond_to do |format|
            format.html
            format.json { render json: {data: Instituition.all.as_json(include:[:instituition_courses]) } }
        end
    end

    def show
        
    end

    def new
        @instituition = Instituition.new
    end

    def create
        @instituition = Instituition.new instituition_params
        if @instituition.save
            redirect_to instituitions_path
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @instituition.update instituition_params
            redirect_to instituitions_path
        else
            render :edit
        end        
    end

    def destroy
        @instituition.destroy
        redirect_to instituitions_path
    end

    private

        def set_instituition
            @instituition = Instituition.find(params[:id])
        end
        
        def instituition_params
            params.require(:instituition).permit(:name, instituition_courses_attributes: [:id, :course_id, :course_evaluation, :students_evaluation, :students_count, :_destroy])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instituitions_helper.rb
module InstituitionsHelper
end

app/views/courses/index.html.erb
<h2>Cursos</h2>
<table class="table courses table-striped">
    <thead>
        <th>#</th>
        <th>Nome</th>
        <th>Nota Geral</th>
        <th>Nº de Alunos</th>
        <th></th>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/instituitions/_form.html.erb
<%= form_for @instituition do |f| %>
    <%= f.submit "Salvar", class: "btn btn-success" %>
    <div class="form-group">
        <h5>Nome</h5>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="instituition-courses row">
        <%= f.fields_for :instituition_courses do |ff| %>
            <%= render "instituition_course_fields", f: ff %>
        <% end %>
        <%= link_to_add_association 'Adicionar Curso', f, :instituition_courses %>
    </div>
<% end %>

app/views/instituitions/_instituition_course_fields.html.erb
<div class="nested-fields col-md-3">
    <div class="form-group">
        <h5>Curso</h5>
        <%= f.select :course_id, options_from_collection_for_select(Course.by_name, "id", "name", f.object.course_id), {}, class: "form-control", required: true %>
    </div>
    <div class="form-group">
        <h5>Avaliação do Curso</h5>
        <%= f.number_field :course_evaluation, step: "0.01", class: "form-control" %>
    </div>
    <div class="form-group">
        <h5>Nota Geral dos Alunos</h5>
        <%= f.number_field :students_evaluation, step: "0.01", class: "form-control" %>
    </div>
    <div class="form-group">
        <h5>Quantidade de Alunos</h5>
        <%= f.number_field :students_count, class: "form-control" %>
    </div>
    <%= link_to_remove_association "Remover Curso", f %>
</div>

app/views/instituitions/edit.html.erb
<h3>Editar Instituição</h3>
<%= render "form" %>
<%= link_to "Remover Instituição", instituition_path(@instituition), class: "btn btn-danger", method: :delete, data: {confirm: "Tem certeza que deseja remover este curso?"} %>

app/views/instituitions/index.html.erb
<h2>Instituições</h2>
<h3><%= link_to "Nova Instituição", new_instituition_path, class: "btn btn-success" %></h3>
<table border="0" cellspacing="5" cellpadding="5">
<table>
    <tbody>
    <tr>
        <td>Nota por Curso Mínima:</td>
        <td><input type="text" id="evaluationMin" name="evaluationMin"></td>
    </tr>
    <tr>
        <td>Nota por Curso Máxima:</td>
        <td><input type="text" id="evaluationMax" name="evaluationMax"></td>
    </tr>
    <tr>
        <td>Nota por Aluno Mínima:</td>
        <td><input type="text" id="studentMin" name="studentMin"></td>
    </tr>
    <tr>
        <td>Nota por Aluno Máxima:</td>
        <td><input type="text" id="studentMax" name="studentMax"></td>
    </tr>
    <tr>
        <td>Curso:</td>
        <td><%= select_tag :course, options_from_collection_for_select(Course.all, "id", "name"), {prompt: "Todos os Cursos"} %></td>
    </tr>
    </tbody>
</table>
<table class="table instituitions table-striped" id="instituitions">
    <thead>
        <th>#</th>
        <th>Nome</th>
        <th>Nota Geral</th>
        <th>Nota dos Alunos</th>
        <th></th>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/instituitions/new.html.erb
<h3>Nova Instituição</h3>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomosEducacao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Somos Educação - Teste</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/instituitions">Instituições <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/courses">Cursos</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="body">
      <%= yield %>
    </div>
  </body>
</html>